version: '3'

services:

  php_service:
    build:
      context: './docker/php'
    container_name: php
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql_service
    links:
      - mysql_service

  nginx_service:
    build:
      context: './docker/nginx'
    container_name: nginx
    depends_on: 
      - 'php_service'
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'

  mysql_service:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    restart: always
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    secrets:
      - db_root_password

  phpmyadmin_service:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_service
    environment:
      PMA_HOST: mysql_service
    restart: always
    ports:
      - 8080:80

secrets:
  db_root_password:
    file: ./db_root_password.txt