
services:

  backend_service:
    build:
      context: './docker/php'
    container_name: php
    volumes:
      - './backend:/var/www/html'
    depends_on:
      - mysql_service
      - redis_service
    links:
      - mysql_service

  frontend_service:
    build:
      context: './docker/node'
    container_name: nodejs
    volumes:
      - './frontend:/app'
    command: bash -c "npm install && npm run dev"

  nginx_service:
    build:
      context: './docker/nginx'
    container_name: nginx
    depends_on: 
      - 'backend_service'
      - 'frontend_service'
    volumes:
      - './backend:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
      - '443:443'

  redis_service:
    build:
      context: './docker/redis'
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'

  mysql_service:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    restart: always
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
      - './docker/mysql/conf.d:/etc/mysql/conf.d'
    secrets:
      - db_root_password

  phpmyadmin_service:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_service
    environment:
      PMA_HOST: mysql_service
    restart: always
    ports:
      - 8080:80

secrets:
  db_root_password:
    file: ./db_root_password.txt
